
apiVersion: v1 
kind: Secret 
metadata: 
  name: payment-secret
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    purpose: secret 
type: Opaque
data:
  AMQP_USER: "cm9ib3Nob3AK"
  AMQP_PASS: "cm9ib3Nob3AxMjMK"

---
apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: payment-config
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    purpose: configmap 
data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"

---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: payment-deploy
  namespace: roboshop
  labels: 
    project: roboshop
    env: dev
    purpose: Deployment 
spec:
  replicas: 2
  selector:
    matchLabels:
      project: roboshop
      env: dev
      component: payment
    
  template:
    metadata:
      labels:
        project: roboshop
        env: dev
        component: payment

    spec:
      containers:
      - name: shipping
        image: manojkoneyagari/payment:2.0
        ports:
        - name: liveness-port
          containerPort: 8080
        startupProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 12
          periodSeconds: 10
        
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 2
          periodSeconds: 10
        
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          periodSeconds: 10

        resources:
          requests:
            cpu: "120m"
            memory: "130Mi"
          limits:
            cpu: "150m"
            memory: "150Mi"

        envFrom:
        - secretRef:
            name: payment-secret
        - configMapRef:
            name: payment-config
        


---
apiVersion: v1
kind: Service 
metadata: 
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    purpose: service 
spec:
  selector:
    project: roboshop
    env: dev
    component: payment

  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080



