---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: shipping-deploy
  namespace: roboshop
  labels: 
    project: roboshop
    env: dev
    purpose: Deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      env: dev
      component: shipping
    
  template:
    metadata:
      labels:
        project: roboshop
        env: dev
        component: shipping

    spec:
      containers:
      - name: shipping
        image: manojkoneyagari/shipping:2.0
        resources:
          requests:
            cpu: "120m"
            memory: "130Mi"
          limits:
            cpu: "150m"
            memory: "150Mi"
        


---
apiVersion: v1
kind: Service 
metadata: 
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    purpose: service 
spec:
  selector:
    project: roboshop
    env: dev
    component: shipping

  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080



