apiVersion: v1 
kind: Secret 
metadata:
  name: rabbitmq-secret
  Namespace: Roboshop
  labels:
    project: roboshop
    env: dev
    purpose: secret 

data:
  RABBITMQ_DEFAULT_USER: "cm9ib3Nob3AK"
  RABBITMQ_DEFAULT_PASS: "cm9ib3Nob3AxMjMK"

---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: rabbitmq-deploy
  Namespace: Roboshop
  labels: 
    project: roboshop
    env: dev
    purpose: Deployment 
spec:
  replicas: 2
  selector:
    matchLabels:
      project: roboshop
      env: dev
      component: rabbitmq
    
  template:
    metadata:
      labels:
        project: roboshop
        env: dev
        component: rabbitmq

    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        resources:
          requests:
            cpu: "120m"
            memory: "130Mi"
          limits:
            cpu: "150m"
            memory: "150Mi"
        envFrom:
        - secretRef:
            name: rabbitmq-secret

---
apiVersion: v1
kind: Service 
metadata: 
  name: rabbitmq-service
  Namespace: Roboshop
  labels:
    project: roboshop
    env: dev
    purpose: service 
spec:
  selector:
    project: roboshop
    env: dev
    component: rabbitmq

  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672



