
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: mongodb-deploy
  namespace: roboshop
  labels: 
    project: roboshop
    env: dev
    purpose: Deployment 
spec:
  replicas: 2
  selector:
    matchLabels:
      project: roboshop
      env: dev
      component: mongodb
    
  template:
    metadata:
      labels:
        project: roboshop
        env: dev
        component: mongodb

    spec:
      containers:
      - name: mongodb
        image: manojkoneyagari/mongodb:2.0
        resources:
          requests:
            cpu: "120m"
            memory: "130Mi"
          limits:
            cpu: "150m"
            memory: "150Mi"


---
apiVersion: v1
kind: Service 
metadata: 
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    purpose: service 
spec:
  selector:
    project: roboshop
    env: dev
    component: mongodb

  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017



