apiVersion: v1 
kind: Secret 
metadata: 
  name: mysql-secret
  Namespace: roboshop
  labels:
    project: roboshop
    env: dev
    purpose: secret
type: Opaque
data: 
  MYSQL_ROOT_PASSWORD: "Um9ib3Nob3BAMQo="

---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: mysql-deploy
  Namespace: roboshop
  labels: 
    project: roboshop
    env: dev
    purpose: Deployment 
spec:
  replicas: 2
  selector:
    matchLabels:
      project: roboshop
      env: dev
      component: mysql
    
  template:
    metadata:
      labels:
        project: roboshop
        env: dev
        component: mysql

    spec:
      containers:
      - name: mysql
        image: manojkoneyagari/mysql:2.0
        resources:
          requests:
            cpu: "120m"
            memory: "130Mi"
          limits:
            cpu: "150m"
            memory: "150Mi"
        args: ["--mysql-native-password=ON"]
        envFrom:
        - secretRef:
            name: mysql-secret

---
apiVersion: v1
kind: Service 
metadata: 
  name: mysql
  Namespace: roboshop
  labels:
    project: roboshop
    env: dev
    purpose: service 
spec:
  selector:
    project: roboshop
    env: dev
    component: mysql

  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306



